
services:
  postgres:
    container_name: spring_demo_db
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_USER: ftsolutionadmin
      POSTGRES_PASSWORD: ftsolution
      POSTGRES_DB: ftsolution_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    container_name: spring_demo_app
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ftsolution_db
      SPRING_DATASOURCE_USERNAME: ftsolutionadmin
      SPRING_DATASOURCE_PASSWORD: ftsolution