version: 2.1

orbs:
  maven: circleci/maven@2.0.0
  heroku: circleci/heroku@2.0.0
  docker: circleci/docker@2.1.4
  postgres: onehq/postgres@1.1.0
  snyk: snyk/snyk@1.5.0

jobs:
  build:
    docker:
      - image: eclipse-temurin:17-jdk-jammy
      - image: postgis/postgis:15-3.3
        environment:
          POSTGRES_USER: ftsolutionadmin
          POSTGRES_PASSWORD: ftsolution
          POSTGRES_DB: ftsolution_db
    steps:
      - checkout
      - run:
          name: Install postgres client
          command: |
            curl -sS https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
            echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
            sudo apt-get update && sudo apt-get install -y postgresql-client-11
      - run:
          name: Install Maven
          command: |
            apt-get update && apt-get install -y maven
      - run:
          name: Install Dependencies
          command: mvn install -DskipTests
  # test:
  #   docker:
  #     - image: eclipse-temurin:17-jdk-jammy
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install Maven
  #         command: |
  #           apt-get update && apt-get install -y maven
  #     - run:
  #         name: Install Dependencies
  #         command: mvn install
  #     - run: |
  #         echo "Running tests"
  #         mvn spring-boot:run

workflows:
  simple_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
