version: 2.1

orbs:
  maven: circleci/maven@2.0.0
  heroku: circleci/heroku@2.0.0
  docker: circleci/docker@2.1.4
  snyk: snyk/snyk@1.5.0

jobs:
  build:
    docker:
      - image: eclipse-temurin:17-jdk-jammy
    steps:
      - checkout
      - maven/install-packages:
          pkg-manager: nvm
      - run: |
          echo "Install dependencies"
          nvm install
  test:
    docker:
      - image: eclipse-temurin:17-jdk-jammy
    steps:
      - checkout
      - maven/install-packages:
          pkg-manager: nvm
      - run: |
          echo "Running tests"
          nvm spring-boot:run

workflows:
  simple_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
