version: 2.1

orbs:
  maven: circleci/maven@2.0.0
  heroku: circleci/heroku@2.0.0
  docker: circleci/docker@2.1.4
  snyk: snyk/snyk@1.5.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:17 # Java 17 image; adjust if you're using a different version
    steps:
      - checkout # Check out the project code
      - restore_cache: # Restore the dependency cache if available
          keys:
            - maven-dependencies-{{ checksum "pom.xml" }}
            - maven-dependencies-
      - run: mvn clean package # Build the project

workflows:
  simple_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
