version: 2.1

orbs:
  maven: circleci/maven@2.0.0
  heroku: circleci/heroku@2.0.0
  docker: circleci/docker@2.1.4
  snyk: snyk/snyk@1.5.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:17 # Java 17 image; adjust if you're using a different version
    steps:
      - checkout # Check out the project code
      - restore_cache: # Restore the dependency cache if available
          keys:
            - maven-dependencies-{{ checksum "pom.xml" }}
            - maven-dependencies-
      - maven/with-cache:
          cache-key: maven-dependencies-{{ checksum "pom.xml" }}
          steps:
            - run: mvn dependency:go-offline # Pre-fetch Maven dependencies
      - run: mvn clean package # Build the project
      - save_cache: # Cache Maven dependencies for faster builds in the future
          paths:
            - ~/.m2
          key: maven-dependencies-{{ checksum "pom.xml" }}
      - store_artifacts: # Save the generated JAR/WAR file
          path: target
          destination: build-artifacts
      - store_test_results: # Save test results for CircleCI's dashboard
          path: target/surefire-reports

workflows:
  simple_workflow:
    jobs:
      - build
