version: 2.1

orbs:
  maven: circleci/maven@2.0.0
  heroku: circleci/heroku@2.0.0
  docker: circleci/docker@2.1.4
  postgres: onehq/postgres@1.1.0
  snyk: snyk/snyk@1.5.0

jobs:
  build:
    docker:
      - image: eclipse-temurin:17-jdk-jammy
      - image: postgis/postgis:15-3.3
        environment:
          POSTGRES_USER: ftsolutionadmin
          POSTGRES_PASSWORD: ftsolution
          POSTGRES_DB: ftsolution_db
    services:
      - postgres
    steps:
      - checkout
      - run:
          name: Install Maven
          command: |
            apt-get update && apt-get install -y maven
      - run:
          name: Install Dependencies
          command: mvn install -DskipTests
  test:
    docker:
      - image: eclipse-temurin:17-jdk-jammy
      - image: postgis/postgis:15-3.3
        environment:
          POSTGRES_HOST: postgres
          POSTGRES_USER: ftsolutionadmin
          POSTGRES_PASSWORD: ftsolution
          POSTGRES_DB: ftsolution_db
    services:
      - postgres
    steps:
      - checkout
      - run:
          name: Install Maven
          command: |
            apt-get update && apt-get install -y maven
      - run:
          name: Install Dependencies
          command: mvn install -DskipTests
      - run: |
          echo "Running tests"
          mvn test

workflows:
  simple_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - release
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - release
